name: Linting

on:
  pull_request:
    branches:
    - master

jobs:
  Linting:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: ./frontend
      run: |
        npm install
      env:
        CI: true
    - name: npm run lint
      working-directory: ./frontend
      run: |
        npm run lint
      env:
        CI: true
